language: node_js
node_js:
- '0.10'
env:
  global:
    secure: ms6pg+JkqhRPO5TtgpxIMxkBbzUUAuK69c+LHgGYNvVdCg9UbUOhiLeyOBW5uaEnLvMSrpEDDrFhIB2YWu18XCu+YaSXODXsRkiXmNda+OXIcN/7SNoIV3W23y3QAcoGwDFmA7UFLCTs3+bMc/sC1bj6hbh1XSIQZ/R7bfwsWRU=
cache:
  directories:
  - node_modules
before_script:
- npm install -g grunt-cli
script:
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run travis; else npm run travis-pr; fi;'
